stages:
    - runSAST

run-sast-job:
    stage: runSAST
    image: maven:3.8.5-f path/to/pom.xml  
    script: |
      mvn -f path/to/pom.xml sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.
      organization=gitlabredseaintegration -Dsonar.projectkey=gitlabredseaintegration -Dsonar
      login=11eb1ca62579608e1d15db4ee917db8d081a2d14
